"""Add coordinates to Inventory

Revision ID: 7de4d74d8aae
Revises: b0bbe6ec6962
Create Date: 2025-05-06 04:52:32.779970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de4d74d8aae'
down_revision = 'b0bbe6ec6962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('coordinates')

    # ### end Alembic commands ###
