"""Add inventory_id to purchases

Revision ID: b0bbe6ec6962
Revises: e3724b94d8b0
Create Date: 2025-05-05 01:20:34.644957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0bbe6ec6962'
down_revision = 'e3724b94d8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('inventory_id')

    # ### end Alembic commands ###
